# Generated by Django 4.2.7 on 2025-05-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimento', models.CharField(choices=[('Feliz', 'Feliz'), ('Irritado', 'Irritado'), ('Triste', 'Triste'), ('Ansioso', 'Ansioso')], max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo'), ('Não sei', 'Não sei')], max_length=20, null=True)),
                ('escala', models.IntegerField()),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='registro.usuario')),
            ],
        ),
    ]
