# Generated by Django 5.2.1 on 2025-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimento', models.CharField(choices=[('Feliz', 'Feliz'), ('Neutro', 'Neutro'), ('Triste', 'Triste'), ('Ansioso', 'Ansioso')], max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo'), ('Não sei', 'Não sei')], max_length=20, null=True)),
                ('escala', models.IntegerField()),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
