# Generated by Django 4.2.7 on 2025-08-02 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimento', models.CharField(choices=[('Feliz', 'Feliz'), ('Irritado', 'Irritado'), ('Triste', 'Triste'), ('Ansioso', 'Ansioso')], max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo'), ('Não sei', 'Não sei')], max_length=20, null=True)),
                ('escala', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_sentimento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_bpm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
