# Generated by Django 4.2.7 on 2025-05-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='escala',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sentimento',
            field=models.CharField(blank=True, choices=[('Feliz', 'Feliz'), ('Irritado', 'Irritado'), ('Triste', 'Triste'), ('Ansioso', 'Ansioso')], max_length=20, null=True),
        ),
    ]
